{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "98d58d04-ca5c-42d6-9a94-da6f6a803e22",
   "metadata": {},
   "source": [
    "\n",
    "# Credit Card Approval Classification Using Machine Learning Classification Models\n",
    "\n",
    "## Problem Statement\n",
    "\n",
    "The objective of this project is to build and compare multiple machine learning classification models for Credit Card Approval Classification. The models are trained on a credit card fillup dataset and evaluated using various performance metrics such as Accuracy, AUC Score, Precision, Recall, F1 Score, and Matthews Correlation Coefficient (MCC).\n",
    "\n",
    "A Streamlit web application is developed to allow users to upload test data, select a machine learning model, and view model evaluation results interactively.\n",
    "\n",
    "---\n",
    "\n",
    "## Dataset Description\n",
    "\n",
    "### Dataset Name\n",
    "Credit Card Filing details Dataset\n",
    "\n",
    "### Source\n",
    "Kaggle\n",
    "\n",
    "### Dataset Characteristics\n",
    "\n",
    "- Total Records: 1549\n",
    "- Total Features: 20\n",
    "- Target Variable: label\n",
    "- Class 0 = Application Approved\n",
    "- Class 1 = Application Rejected\n",
    "\n",
    "### Features\n",
    "\n",
    "The dataset contains:\n",
    "```text\n",
    "-Ind_ID: Client ID\n",
    "-Gender: Gender information\n",
    "-Car_owner: Having car or not\n",
    "-Propert_owner: Having property or not\n",
    "-Children: Count of children\n",
    "-Annual_income: Annual income\n",
    "-Type_Income: Income type\n",
    "-Education: Education level\n",
    "-Marital_status: Marital_status\n",
    "-Housing_type: Living style\n",
    "-Birthday_count: Use backward count from current day (0), -1 means yesterday.\n",
    "-Employed_days: Start date of employment. Use backward count from current day (0). Positive value means, individual is currently unemployed.\n",
    "-Mobile_phone: Any mobile phone\n",
    "-Work_phone: Any work phone\n",
    "-Phone: Any phone number\n",
    "-EMAIL_ID: Any email ID\n",
    "-Type_Occupation: Occupation\n",
    "-Family_Members: Family size\n",
    "-Another data set (Credit_card_label.csv) contains two key pieces of information\n",
    "-ID: The joining key between application data and credit status data, same is Ind_ID\n",
    "-Label: 0 is application approved and 1 is application rejected\n",
    "```\n",
    "\n",
    "The dataset satisfies the assignment requirements:\n",
    "\n",
    "- Number of Instances > 500\n",
    "- Number of Features > 12\n",
    "\n",
    "---\n",
    "\n",
    "## Project Structure\n",
    "\n",
    "```text\n",
    "ML_Assignment_2/\n",
    "│\n",
    "├── app.py\n",
    "├── requirements.txt\n",
    "├── README.md\n",
    "├── test_data.csv\n",
    "│\n",
    "├── dataset/\n",
    "│   ├── Credit_card.csv\n",
    "│   └── data_preprocessing.py\n",
    "│\n",
    "├── models/\n",
    "│   ├── logistic_regression.py\n",
    "│   ├── decision_tree.py\n",
    "│   ├── knn_classifier.py\n",
    "│   ├── naive_bayes.py\n",
    "│   ├── random_forest.py\n",
    "│   └── evaluation.py\n",
    "│\n",
    "├── saved_models/\n",
    "│\n",
    "└── results/\n",
    "```\n",
    "\n",
    "## Github Repository Link Repository URL:\n",
    "URL :\n",
    "\n",
    "## Streamlit Application Link\n",
    "URL :\n",
    "\n",
    "\n",
    "## Machine Learning Models Implemented\n",
    "Logistic Regression\n",
    "Decision Tree Classifier\n",
    "K-Nearest Neighbors (KNN)\n",
    "Gaussian Naive Bayes\n",
    "Random Forest Classifier\n",
    "Evaluation Metrics\n",
    "\n",
    "## The following evaluation metrics are used:\n",
    "Accuracy\n",
    "AUC Score\n",
    "Precision\n",
    "Recall\n",
    "F1 Score\n",
    "Matthews Correlation Coefficient (MCC)\n",
    "\n",
    "\n",
    "\n",
    "| Model               |   Accuracy |   AUC Score |   Precision |    Recall |   F1 Score |   MCC Score |\n",
    "|:--------------------|-----------:|------------:|------------:|----------:|-----------:|------------:|\n",
    "| Logistic Regression |   0.892683 |    0.679086 |    0        | 0         |   0        |    0        |\n",
    "| Decision Tree       |   0.873171 |    0.749006 |    0.433333 | 0.590909  |   0.5      |    0.436112 |\n",
    "| KNN                 |   0.887805 |    0.709389 |    0.4      | 0.0909091 |   0.148148 |    0.149515 |\n",
    "| Naive Bayes         |   0.892683 |    0.576751 |    0        | 0         |   0        |    0        |\n",
    "| Random Forest       |   0.936585 |    0.861898 |    0.846154 | 0.5       |   0.628571 |    0.621136 |\n",
    "\n",
    "## Observation on result\n",
    "\n",
    "| Model | Observation |\n",
    "|---------|-------------|\n",
    "| **Logistic Regression** | Achieved **89.27% accuracy**, but failed to identify any positive class instances, resulting in **Precision, Recall, F1-Score, and MCC of 0**. Although the **AUC Score (0.679)** indicates moderate discrimination ability, the model did not effectively handle the minority class. High accuracy is misleading due to class imbalance. |\n",
    "| **Decision Tree** | Achieved **87.32% accuracy** with a balanced performance across minority class metrics. It recorded **43.33% Precision**, **59.09% Recall**, **50% F1-Score**, and **0.436 MCC**, indicating a reasonable ability to detect positive cases. Suitable as an interpretable baseline model. |\n",
    "| **K-Nearest Neighbors (KNN)** | Achieved **88.78% accuracy** and **0.709 AUC Score**, but suffered from very low **Recall (9.09%)**, meaning most positive cases were missed. The low **F1-Score (14.81%)** and **MCC (0.150)** indicate limited effectiveness for detecting the minority class. |\n",
    "| **Naïve Bayes** | Produced **89.27% accuracy**, but failed to classify any positive instances, resulting in **Precision, Recall, F1-Score, and MCC of 0**. With the lowest **AUC Score (0.577)** among all models, it demonstrated poor classification performance on this dataset. |\n",
    "| **Random Forest** | Delivered the **best overall performance** with **93.66% Accuracy**, **0.862 AUC Score**, **84.62% Precision**, **50% Recall**, **62.86% F1-Score**, and **0.621 MCC**. It effectively balanced predictive performance and minority class detection, making it the most suitable model for deployment. |\n",
    "\n",
    "## Overall feedback\n",
    "\n",
    "> **Conclusion:** The dataset appears to be imbalanced, as some models achieved high accuracy while failing to predict any positive instances. Therefore, metrics such as **AUC Score, Recall, F1-Score, and MCC** provide a more reliable assessment than accuracy alone. Among all evaluated models, **Random Forest** demonstrated the best overall performance and is recommended as the final model.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04998e79-2a2e-4f9d-b3f1-7a9661abe1f8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "10e39d4f-eb06-4856-80cd-ebea5a64679e",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d90e530-a5c3-4e4b-83bf-fc4303174b6f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
